apiVersion: v1
kind: Service
metadata:
  name: guestbook-service
  labels:
    app: guestbook-service
    tier: frontend

spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30008
  selector:
    app: guestbook-pod
    tier: frontend