apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-deployment
  labels:
    app: guestbook-app
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guestbook-pod
      tier: frontend
  template:
    metadata:
      name: guestbook-pod
      labels:
        app: guestbook-pod
        tier: frontend
    spec:
      containers:
        - name: guestbook
          image: kubernetes/guestbook:v2
          ports:
            - containerPort: 3000