apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    name: redis-service
    tier: backend
spec:
  selector:
    app: redis
    tier: backend
    role: master
  ports:
    - port: 6379
      targetPort: 6379