apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  labels:
    name: redis-service
    tier: backend
spec:
  selector:
    app: redis
    tier: backend
    role: slave
  ports:
    - port: 6379
      targetPort: 6379