apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave-deployment
  labels:
    name: redis-slave-deployment
    role: slave
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
      tier: backend
      role: slave
  template:
    metadata:
      name: redis-slave
      labels:
        app: redis
        tier: backend
        role: slave
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379